#.travis.yml
sudo: false
dist: trusty

language: node_js
node_js:
  - "6.10.1"

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g firebase-tools

script:
  - ng lint
  - ng test --watch=false --cc
  - codecov -f coverage/*.json
  - ng e2e
  - ng build --prod

before_deploy:
  - gfp

deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change