#.travis.yml

language: node_js
node_js:
  - "6.10.1"

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - npm run precache

notifications:
  email:
    on_failure: change
    on_success: change

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master